### ISSUE TITLE
Filewatcherd fails to start (Bad file descriptor)

### ISSUE THREAD

**Issue by F2N** [faelys/filewatcherd#2]
Hi,

Under FreeBSD 10.1 I installed filewatcherd but each time I try to launch I get an error 

Oct  9 18:06:51 famp filewatcherd: Error while waiting for a kevent: Bad file descriptor
Oct  9 18:14:49 famp root: /usr/local/etc/rc.d/filewatcherd: WARNING: failed to start filewatcherd

Here is the full description of the issue with more input from other users

https://forums.freebsd.org/threads/filewatcherd-fails-to-start-bad-file-descriptor.53527/

**Comment by faelys** [comment]
I think this is corrected by 783951da990a5b, but that was committed after the port creation. I tried to get the port updated a long while ago, but gave up when the PR didn't seem to get any attention.

I planned on trying again before the end of the year, after I've committed man pages, but I can try to re-prioritize it since there seems to be interest I was unaware of.

**Comment by F2N** [comment]
There is a huge interest in it since there is not - in my knowledge - an alternative to incron for FreeBSD, how can I resolve the issue since the soft is installed from the ports ? should I wait for you to commit the changes so they can be exported to the ports ? Thank you for your answers and responsiveness and above all for this magnificent piece of soft.

**Comment by faelys** [comment]
If you compile your own ports (either by using the ports directly or by using binary packages you built yourself), you can simply save the commit diff as `sysutils/filewatcherd/files/patch-filewatcherd.c` and rebuild/reinstall the port.

If you use the official binary packages, or some reason have use a pristine ports tree, you will have to wait for an official update of the ports tree. That will happen in a few steps:

- First I release a real 1.0 version, with man pages, and open a PR to update the ports. That demends completely on me, and I don't think you can do anything in this step. I expect it to be able to complete it at best within 8 hours from now, at worst during next week-end.

- Second, someone with a commit bit has to take care of the PR and actually update the official ports tree. If you know (or are) a committer, you can greatly help by convincing them to do that. That is the part that can go on for ever, and I don't really have any power over it. I guess the more interest the ports or the PR generates, the easier it is to motive a committer to take care of it.

- Third, if you use official binary packages, once the port is updated you have to wait for the package to be rebuilt, which happens weekly. I don't think anyone can do anything to help this step.

Thanks a lot for your interest and you kind words. (My responsiveness here is a fluke, usually it takes me a few hours to a day.)

**Comment by F2N** [comment]
En tout cas merci, je pense que je patienterais le temps que tu fasses le commit, j'utilises portmaster pour compiler mes ports et les installer, mais je n'ai jamais fait de telles modifications, par ailleurs c'est quoi un PR ? Merci.

**Comment by faelys** [comment]
PR c'est l'abbréviation de Problem Report, c'était le nom des tickets de FreeBSD lorsqu'ils utilisaient encore GNATS (il me semble que la commande `send-pr` existe encore dans FreeBSD 10). J'imagine qu'il faudrait dire « bug » maintenant qu'ils sont passés à bugzilla, même si ce n'est pas un bug au sens habituel du mot, c'est plutôt une demande d'évolution.

**Comment by faelys** [comment]
So for anyone who is following this, I have just created a release called "1.0-beta3" (that will be 1.0 if nobody reports any issue about the code or the manpages for a while), and I have submitted [bug 203881](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203881) to include the update in the official ports tree.

So now, as far as I know, I have done all could, everything else is in the committers' hands.

**Comment by F2N** [comment]
Thanks a lot for all you have done, I hope you'll be able to release a stable version, and I hope you have a lot of luck in your life and projects.

**Comment by F2N** [comment]
This issue is solved 

root@famp:/tmp # service filewatcherd start
Starting filewatcherd.
Watchtab "/usr/local/etc/watchtab" loaded successfully
root@famp:/tmp # service filewatcherd status
filewatcherd is running as pid 37187.
